// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\SivapriyaAnbu\Documents\golang_training\golang_training_sivapriya\Projects\Event-booking_management\src\daos\refresh-token.go

// Package mock_daos is a generated GoMock package.
package mock_daos

import (
	models "event-booking/database/models"
	context "event-booking/utils/context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRefreshTokenDAO is a mock of RefreshTokenDAO interface.
type MockRefreshTokenDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenDAOMockRecorder
}

// MockRefreshTokenDAOMockRecorder is the mock recorder for MockRefreshTokenDAO.
type MockRefreshTokenDAOMockRecorder struct {
	mock *MockRefreshTokenDAO
}

// NewMockRefreshTokenDAO creates a new mock instance.
func NewMockRefreshTokenDAO(ctrl *gomock.Controller) *MockRefreshTokenDAO {
	mock := &MockRefreshTokenDAO{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenDAO) EXPECT() *MockRefreshTokenDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenDAO) Create(ctx *context.Context, refreshToken *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenDAOMockRecorder) Create(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenDAO)(nil).Create), ctx, refreshToken)
}

// Delete mocks base method.
func (m *MockRefreshTokenDAO) Delete(ctx *context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenDAOMockRecorder) Delete(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenDAO)(nil).Delete), ctx, token)
}

// Get mocks base method.
func (m *MockRefreshTokenDAO) Get(ctx *context.Context, token string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, token)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRefreshTokenDAOMockRecorder) Get(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRefreshTokenDAO)(nil).Get), ctx, token)
}

// Update mocks base method.
func (m *MockRefreshTokenDAO) Update(ctx *context.Context, id string, updatedSchedule *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, updatedSchedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefreshTokenDAOMockRecorder) Update(ctx, id, updatedSchedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshTokenDAO)(nil).Update), ctx, id, updatedSchedule)
}

// Upsert mocks base method.
func (m *MockRefreshTokenDAO) Upsert(ctx *context.Context, refreshToken *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRefreshTokenDAOMockRecorder) Upsert(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRefreshTokenDAO)(nil).Upsert), ctx, refreshToken)
}
